In [227]:
import pandas as pd
ds = pd.read_csv('nba.csv')
print(ds.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1340 entries, 0 to 1339
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Name         1340 non-null   object 
 1   GP           1340 non-null   int64  
 2   MIN          1340 non-null   float64
 3   PTS          1340 non-null   float64
 4   FGM          1340 non-null   float64
 5   FGA          1340 non-null   float64
 6   FG%          1340 non-null   float64
 7   3P Made      1340 non-null   float64
 8   3PA          1340 non-null   float64
 9   3P%          1329 non-null   float64
 10  FTM          1340 non-null   float64
 11  FTA          1340 non-null   float64
 12  FT%          1340 non-null   float64
 13  OREB         1340 non-null   float64
 14  DREB         1340 non-null   float64
 15  REB          1340 non-null   float64
 16  AST          1340 non-null   float64
 17  STL          1340 non-null   float64
 18  BLK          1340 non-null   float64
 19  TOV   

In [228]:
print(ds.columns)

Index(['Name', 'GP', 'MIN', 'PTS', 'FGM', 'FGA', 'FG%', '3P Made', '3PA',
       '3P%', 'FTM', 'FTA', 'FT%', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK',
       'TOV', 'TARGET_5Yrs'],
      dtype='object')


In [229]:
ds.head()

Name  GP   MIN  PTS  FGM  FGA   FG%  3P Made  3PA   3P%  ...  \
0   Brandon Ingram  36  27.4  7.4  2.6  7.6  34.7      0.5  2.1  25.0  ...   
1  Andrew Harrison  35  26.9  7.2  2.0  6.7  29.6      0.7  2.8  23.5  ...   
2   JaKarr Sampson  74  15.3  5.2  2.0  4.7  42.2      0.4  1.7  24.4  ...   
3      Malik Sealy  58  11.6  5.7  2.3  5.5  42.6      0.1  0.5  22.6  ...   
4      Matt Geiger  48  11.5  4.5  1.6  3.0  52.4      0.0  0.1   0.0  ...   

   FTA   FT%  OREB  DREB  REB  AST  STL  BLK  TOV  TARGET_5Yrs  
0  2.3  69.9   0.7   3.4  4.1  1.9  0.4  0.4  1.3          0.0  
1  3.4  76.5   0.5   2.0  2.4  3.7  1.1  0.5  1.6          0.0  
2  1.3  67.0   0.5   1.7  2.2  1.0  0.5  0.3  1.0          0.0  
3  1.3  68.9   1.0   0.9  1.9  0.8  0.6  0.1  1.0          1.0  
4  1.9  67.4   1.0   1.5  2.5  0.3  0.3  0.4  0.8          1.0  

[5 rows x 21 columns]

In [230]:
ds = ds.dropna()
ds.shape

(1329, 21)

In [231]:
f = ds.drop(columns=['Name'])
l = ds['Name']
print('sahape of features :',f.shape)
print('shape of labels :',l.shape)

sahape of features : (1329, 20)
shape of labels : (1329,)


In [232]:
from sklearn.model_selection import train_test_split
x1_train, x1_test, y1_train, y1_test = train_test_split(f, l, test_size=0.2, random_state=42)

In [233]:
print(x1_train.shape)
print(x1_test.shape)
print(y1_train.shape)
print(y1_test.shape)
split_ratio = len(x1_train) / len(x1_test)
print("The train to test split ratio is :", split_ratio)

(1063, 20)
(266, 20)
(1063,)
(266,)
The train to test split ratio is : 3.9962406015037595


In [234]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x1_train = scaler.fit_transform(x1_train)
x1_test = scaler.transform(x1_test)
logreg = LogisticRegression()


logreg.fit(x1_train, y1_train)
y1_pred = logreg.predict(x1_test)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [235]:
print("Accuracy:", accuracy_score(y1_test, y1_pred))
print('f1 score :',f1_score(y1_test, y1_pred, average='weighted'))
print('precision :',precision_score(y1_test, y1_pred, average='weighted'))
print('recall score :',recall_score(y1_test, y1_pred, average='weighted'))

Accuracy: 0.015037593984962405
f1 score : 0.015037593984962405
precision : 0.015037593984962405
recall score : 0.015037593984962405


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [236]:
from sklearn.svm import SVC
svm_model = SVC(kernel='linear')
svm_model.fit(x1_train, y1_train)
y1_predsvm = svm_model.predict(x1_test)
accuracy_svm = accuracy_score(y1_test, y1_predsvm)
f1_svm = f1_score(y1_test, y1_predsvm, average='weighted')
prec_svm = precision_score(y1_test, y1_predsvm, average='weighted')
rec_svm = recall_score(y1_test, y1_predsvm, average='weighted')
print({'Accuracy: {accuracy_svm}'})
print(f'F1 Score: {f1_svm}')
print(f'Precision: {prec_svm}')
print(f'Recall: {rec_svm}')

{'Accuracy: {accuracy_svm}'}
F1 Score: 0.015037593984962405
Precision: 0.013157894736842105
Recall: 0.018796992481203006


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [237]:

df = pd.read_csv('social_well_being.csv')
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 924 entries, 0 to 923
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype 
---  ------                      --------------  ----- 
 0   User_ID                     924 non-null    int64 
 1   Age                         924 non-null    int64 
 2   Gender                      924 non-null    object
 3   Platform                    924 non-null    object
 4   Daily_Usage_Time (minutes)  924 non-null    int64 
 5   Posts_Per_Day               924 non-null    int64 
 6   Likes_Received_Per_Day      924 non-null    int64 
 7   Comments_Received_Per_Day   924 non-null    int64 
 8   Messages_Sent_Per_Day       924 non-null    int64 
 9   Dominant_Emotion            924 non-null    object
dtypes: int64(7), object(3)
memory usage: 72.3+ KB
None


In [238]:
print(df.columns)

Index(['User_ID', 'Age', 'Gender', 'Platform', 'Daily_Usage_Time (minutes)',
       'Posts_Per_Day', 'Likes_Received_Per_Day', 'Comments_Received_Per_Day',
       'Messages_Sent_Per_Day', 'Dominant_Emotion'],
      dtype='object')


In [239]:
df.head()

User_ID  Age      Gender   Platform  Daily_Usage_Time (minutes)  \
0        1   25      Female  Instagram                         120   
1        2   30        Male    Twitter                          90   
2        3   22  Non-binary   Facebook                          60   
3        4   28      Female  Instagram                         200   
4        5   33        Male   LinkedIn                          45   

   Posts_Per_Day  Likes_Received_Per_Day  Comments_Received_Per_Day  \
0              3                      45                         10   
1              5                      20                         25   
2              2                      15                          5   
3              8                     100                         30   
4              1                       5                          2   

   Messages_Sent_Per_Day Dominant_Emotion  
0                     12        Happiness  
1                     30            Anger  
2                     20          Neutral  
3                     50          Anxiety  
4                     10          Boredom

In [240]:
print('the classes are :',df['Dominant_Emotion'].unique())

the classes are : ['Happiness' 'Anger' 'Neutral' 'Anxiety' 'Boredom' 'Sadness']


In [241]:
print('the genders are :',df['Gender'].unique())
print('the platforms used are :',df['Platform'].unique())

the genders are : ['Female' 'Male' 'Non-binary']
the platforms used are : ['Instagram' 'Twitter' 'Facebook' 'LinkedIn' 'Whatsapp' 'Telegram'
 'Snapchat']


In [242]:
df = pd.get_dummies(df,columns=['Gender'],prefix='',prefix_sep='',dtype=int)
df

User_ID  Age   Platform  Daily_Usage_Time (minutes)  Posts_Per_Day  \
0          1   25  Instagram                         120              3   
1          2   30    Twitter                          90              5   
2          3   22   Facebook                          60              2   
3          4   28  Instagram                         200              8   
4          5   33   LinkedIn                          45              1   
..       ...  ...        ...                         ...            ...   
919      996   33    Twitter                          85              4   
920      997   22   Facebook                          70              1   
921      998   35   Whatsapp                         110              3   
922      999   28   Telegram                          60              2   
923     1000   27   Snapchat                         120              4   

     Likes_Received_Per_Day  Comments_Received_Per_Day  Messages_Sent_Per_Day  \
0                        45                         10                     12   
1                        20                         25                     30   
2                        15                          5                     20   
3                       100                         30                     50   
4                         5                          2                     10   
..                      ...                        ...                    ...   
919                      35                         18                     18   
920                      14                          6                     10   
921                      50                         25                     25   
922                      18                          8                     18   
923                      40                         18                     22   

    Dominant_Emotion  Female  Male  Non-binary  
0          Happiness       1     0           0  
1              Anger       0     1           0  
2            Neutral       0     0           1  
3            Anxiety       1     0           0  
4            Boredom       0     1           0  
..               ...     ...   ...         ...  
919          Boredom       0     0           1  
920          Neutral       1     0           0  
921        Happiness       0     1           0  
922            Anger       0     0           1  
923          Neutral       1     0           0  

[924 rows x 12 columns]

In [243]:
df = pd.get_dummies(df,columns=['Platform'],prefix='',prefix_sep='',dtype=int)
df

User_ID  Age  Daily_Usage_Time (minutes)  Posts_Per_Day  \
0          1   25                         120              3   
1          2   30                          90              5   
2          3   22                          60              2   
3          4   28                         200              8   
4          5   33                          45              1   
..       ...  ...                         ...            ...   
919      996   33                          85              4   
920      997   22                          70              1   
921      998   35                         110              3   
922      999   28                          60              2   
923     1000   27                         120              4   

     Likes_Received_Per_Day  Comments_Received_Per_Day  Messages_Sent_Per_Day  \
0                        45                         10                     12   
1                        20                         25                     30   
2                        15                          5                     20   
3                       100                         30                     50   
4                         5                          2                     10   
..                      ...                        ...                    ...   
919                      35                         18                     18   
920                      14                          6                     10   
921                      50                         25                     25   
922                      18                          8                     18   
923                      40                         18                     22   

    Dominant_Emotion  Female  Male  Non-binary  Facebook  Instagram  LinkedIn  \
0          Happiness       1     0           0         0          1         0   
1              Anger       0     1           0         0          0         0   
2            Neutral       0     0           1         1          0         0   
3            Anxiety       1     0           0         0          1         0   
4            Boredom       0     1           0         0          0         1   
..               ...     ...   ...         ...       ...        ...       ...   
919          Boredom       0     0           1         0          0         0   
920          Neutral       1     0           0         1          0         0   
921        Happiness       0     1           0         0          0         0   
922            Anger       0     0           1         0          0         0   
923          Neutral       1     0           0         0          0         0   

     Snapchat  Telegram  Twitter  Whatsapp  
0           0         0        0         0  
1           0         0        1         0  
2           0         0        0         0  
3           0         0        0         0  
4           0         0        0         0  
..        ...       ...      ...       ...  
919         0         0        1         0  
920         0         0        0         0  
921         0         0        0         1  
922         0         1        0         0  
923         1         0        0         0  

[924 rows x 18 columns]

In [244]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['Dominant_Emotion'] = label_encoder.fit_transform(df['Dominant_Emotion'])
df

User_ID  Age  Daily_Usage_Time (minutes)  Posts_Per_Day  \
0          1   25                         120              3   
1          2   30                          90              5   
2          3   22                          60              2   
3          4   28                         200              8   
4          5   33                          45              1   
..       ...  ...                         ...            ...   
919      996   33                          85              4   
920      997   22                          70              1   
921      998   35                         110              3   
922      999   28                          60              2   
923     1000   27                         120              4   

     Likes_Received_Per_Day  Comments_Received_Per_Day  Messages_Sent_Per_Day  \
0                        45                         10                     12   
1                        20                         25                     30   
2                        15                          5                     20   
3                       100                         30                     50   
4                         5                          2                     10   
..                      ...                        ...                    ...   
919                      35                         18                     18   
920                      14                          6                     10   
921                      50                         25                     25   
922                      18                          8                     18   
923                      40                         18                     22   

     Dominant_Emotion  Female  Male  Non-binary  Facebook  Instagram  \
0                   3       1     0           0         0          1   
1                   0       0     1           0         0          0   
2                   4       0     0           1         1          0   
3                   1       1     0           0         0          1   
4                   2       0     1           0         0          0   
..                ...     ...   ...         ...       ...        ...   
919                 2       0     0           1         0          0   
920                 4       1     0           0         1          0   
921                 3       0     1           0         0          0   
922                 0       0     0           1         0          0   
923                 4       1     0           0         0          0   

     LinkedIn  Snapchat  Telegram  Twitter  Whatsapp  
0           0         0         0        0         0  
1           0         0         0        1         0  
2           0         0         0        0         0  
3           0         0         0        0         0  
4           1         0         0        0         0  
..        ...       ...       ...      ...       ...  
919         0         0         0        1         0  
920         0         0         0        0         0  
921         0         0         0        0         1  
922         0         0         1        0         0  
923         0         1         0        0         0  

[924 rows x 18 columns]

In [245]:

x = df.drop(['Dominant_Emotion'],axis=1)
y = df['Dominant_Emotion']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=32)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)
split_ratio = len(x_train) / len(x_test)
print("The train-to-test split ratio is:", split_ratio)

(739, 17)
(185, 17)
(739,)
(185,)
The train-to-test split ratio is: 3.9945945945945946


In [246]:
# from sklearn.neighbors import KNeighborsClassifier
# from sklearn.metrics import accuracy_score
# knn= KNeighborsClassifier(n_neighbors=5)
# knn.fit(x_train,y_train)
# y_pred = knn.predict(x_test)
# print(accuracy_score(y_test,y_pred))

In [247]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(x_train)
X_test_scaled = scaler.transform(x_test)
param_grid = {'n_neighbors': range(1, 21)}
knn = KNeighborsClassifier()
grid_search = GridSearchCV(knn, param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train_scaled, y_train)
best_knn = grid_search.best_estimator_
best_knn.fit(X_train_scaled, y_train)
y_pred = best_knn.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred)
print("Model accuracy:", accuracy)
print("Best number of neighbors:", grid_search.best_params_['n_neighbors'])


Model accuracy: 0.9567567567567568
Best number of neighbors: 1


In [248]:
ypred = pd.DataFrame({'Dominant_Emotion_encoded_predicted': y_pred})
ypred

Dominant_Emotion_encoded_predicted
0                                     4
1                                     3
2                                     4
3                                     0
4                                     3
..                                  ...
180                                   1
181                                   0
182                                   5
183                                   4
184                                   3

[185 rows x 1 columns]

In [249]:
predicted = label_encoder.inverse_transform(y_pred)
print(predicted)

['Neutral' 'Happiness' 'Neutral' 'Anger' 'Happiness' 'Boredom' 'Happiness'
 'Neutral' 'Sadness' 'Anger' 'Neutral' 'Neutral' 'Boredom' 'Anger'
 'Sadness' 'Anxiety' 'Anxiety' 'Anger' 'Boredom' 'Neutral' 'Happiness'
 'Neutral' 'Sadness' 'Neutral' 'Neutral' 'Anxiety' 'Sadness' 'Neutral'
 'Happiness' 'Neutral' 'Boredom' 'Sadness' 'Neutral' 'Sadness' 'Happiness'
 'Sadness' 'Neutral' 'Neutral' 'Anger' 'Anger' 'Happiness' 'Neutral'
 'Boredom' 'Happiness' 'Sadness' 'Sadness' 'Happiness' 'Anxiety' 'Anger'
 'Anxiety' 'Anxiety' 'Anxiety' 'Happiness' 'Boredom' 'Anxiety' 'Neutral'
 'Neutral' 'Happiness' 'Anxiety' 'Neutral' 'Sadness' 'Happiness' 'Anger'
 'Happiness' 'Boredom' 'Happiness' 'Happiness' 'Anxiety' 'Sadness'
 'Sadness' 'Anxiety' 'Boredom' 'Sadness' 'Anxiety' 'Anxiety' 'Happiness'
 'Happiness' 'Sadness' 'Neutral' 'Neutral' 'Sadness' 'Neutral' 'Sadness'
 'Happiness' 'Anxiety' 'Anxiety' 'Neutral' 'Anger' 'Neutral' 'Neutral'
 'Anxiety' 'Happiness' 'Anxiety' 'Happiness' 'Anger' 'Happiness' 'Ang

In [250]:
from sklearn.metrics import confusion_matrix, classification_report
conf_matrix = confusion_matrix(y_test, y_pred)
print("The confusion matrix is:")
print(conf_matrix)
class_report = classification_report(y_test, y_pred, target_names=['Anger', 'Anxiety', 'Boredom', 'Happiness', 'Neutral', 'Sadness'])
print("The classification report is:")
print(class_report)


The confusion matrix is:
[[21  0  0  0  0  2]
 [ 1 32  0  0  0  0]
 [ 0  0 23  0  0  0]
 [ 0  0  0 37  0  0]
 [ 0  0  4  0 37  0]
 [ 0  0  1  0  0 27]]
The classification report is:
              precision    recall  f1-score   support

       Anger       0.95      0.91      0.93        23
     Anxiety       1.00      0.97      0.98        33
     Boredom       0.82      1.00      0.90        23
   Happiness       1.00      1.00      1.00        37
     Neutral       1.00      0.90      0.95        41
     Sadness       0.93      0.96      0.95        28

    accuracy                           0.96       185
   macro avg       0.95      0.96      0.95       185
weighted avg       0.96      0.96      0.96       185



In [251]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

nb = GaussianNB()

nb.fit(X_train_scaled, y_train)
y_pred_nb = nb.predict(X_test_scaled)
accuracy_nb = accuracy_score(y_test, y_pred_nb)
print("Model accuracy:", accuracy_nb)
conf_matrix_nb = confusion_matrix(y_test, y_pred_nb)
print("The confusion matrix is:")
print(conf_matrix_nb)

class_report_nb = classification_report(y_test, y_pred_nb, target_names=['Anger', 'Anxiety', 'Boredom', 'Happiness', 'Neutral', 'Sadness'])
print("The classification report is:")
print(class_report_nb)


Model accuracy: 0.42702702702702705
The confusion matrix is:
[[22  0  1  0  0  0]
 [ 7  0 17  7  0  2]
 [ 4  0 19  0  0  0]
 [ 3  0  0 31  0  3]
 [12  0 21  7  0  1]
 [ 9  0  9  3  0  7]]
The classification report is:
              precision    recall  f1-score   support

       Anger       0.39      0.96      0.55        23
     Anxiety       0.00      0.00      0.00        33
     Boredom       0.28      0.83      0.42        23
   Happiness       0.65      0.84      0.73        37
     Neutral       0.00      0.00      0.00        41
     Sadness       0.54      0.25      0.34        28

    accuracy                           0.43       185
   macro avg       0.31      0.48      0.34       185
weighted avg       0.29      0.43      0.32       185



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [252]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import GridSearchCV
param_grid_dt = {'criterion': ['gini', 'entropy'],'max_depth': [None, 10, 20, 30, 40, 50],'min_samples_split': [2, 5, 10],'min_samples_leaf': [1, 2, 4]}
dt = DecisionTreeClassifier()
grid_search_dt = GridSearchCV(dt, param_grid_dt, cv=5, scoring='accuracy')
grid_search_dt.fit(X_train_scaled, y_train)


best_dt = grid_search_dt.best_estimator_
best_dt.fit(X_train_scaled, y_train)

y_pred_dt = best_dt.predict(X_test_scaled)

accuracy_dt = accuracy_score(y_test, y_pred_dt)
print("Decision Tree model accuracy:", accuracy_dt)

conf_matrix_dt = confusion_matrix(y_test, y_pred_dt)
print("The confusion matrix is:")
print(conf_matrix_dt)
class_report_dt = classification_report(y_test, y_pred_dt, target_names=['Anger', 'Anxiety', 'Boredom', 'Happiness', 'Neutral', 'Sadness'])
print("The classification report is:")
print(class_report_dt)


Decision Tree model accuracy: 0.9459459459459459
The confusion matrix is:
[[20  0  1  0  1  1]
 [ 0 33  0  0  0  0]
 [ 1  0 22  0  0  0]
 [ 0  0  0 35  0  2]
 [ 1  0  0  0 40  0]
 [ 1  1  1  0  0 25]]
The classification report is:
              precision    recall  f1-score   support

       Anger       0.87      0.87      0.87        23
     Anxiety       0.97      1.00      0.99        33
     Boredom       0.92      0.96      0.94        23
   Happiness       1.00      0.95      0.97        37
     Neutral       0.98      0.98      0.98        41
     Sadness       0.89      0.89      0.89        28

    accuracy                           0.95       185
   macro avg       0.94      0.94      0.94       185
weighted avg       0.95      0.95      0.95       185



In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import numpy as np
param_dist_rf = {'n_estimators': [50, 100, 200],'criterion': ['gini', 'entropy'],'max_depth': [None, 10, 20, 30],'min_samples_split': [2, 5, 10],'min_samples_leaf': [1, 2, 4],'bootstrap': [True, False]}

rf = RandomForestClassifier()
random_search_rf = RandomizedSearchCV(rf, param_distributions=param_dist_rf, n_iter=50, cv=5, scoring='accuracy', random_state=42, n_jobs=-1)
random_search_rf.fit(X_train_scaled, y_train)

best_rf = random_search_rf.best_estimator_
best_rf.fit(X_train_scaled, y_train)
y_pred_rf = best_rf.predict(X_test_scaled)
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print("Random Forest model accuracy:", accuracy_rf)
conf_matrix_rf = confusion_matrix(y_test, y_pred_rf)
print("The confusion matrix is:")
print(conf_matrix_rf)
class_report_rf = classification_report(y_test, y_pred_rf, target_names=['Anger', 'Anxiety', 'Boredom', 'Happiness', 'Neutral', 'Sadness'])
print("The classification report is:")
print(class_report_rf)


In [ ]:
data = pd.read_csv('iris.csv')
data

In [ ]:
print(data.info())
ssu = pd.DataFrame(data.describe())
ssu

In [ ]:
import seaborn as sns
sns.pairplot(data,diag_kind = 'kde')

In [ ]:
from sklearn.cluster import KMeans
cluster = KMeans(n_clusters=3, random_state=42)
cluster_labels = cluster.fit_predict(data,3)
print(cluster_labels)
data['cluster'] = cluster_labels
data

In [ ]:
import matplotlib.pyplot as plt
sns.pairplot(data, hue='cluster', palette='Set2')
plt.show()